### ISSUE TITLE
genomeassembly usage

### ISSUE THREAD

**Issue by abdo3a** [sanger-tol/genomeassembly#34]
Hi There,
I'm so happy that this pipeline has been released, I was looking forward to using it.
But while trying it on my data, I realized that the HiC dataset needs to be in .CRAM but I have it as paired .FASTQ (F and R).

**Comment by yumisims** [comment]
you could convert your fastq file to cram using samtools import, eg.
samtools import -@88 -r ID:${prefix} -r CN:${hic_kit} -r PU:${prefix} -r SM:${sample_name} $r1.fastq.gz $r2.fastq.gz -o ${prefix}.cram
samtool index ${prefix}.cram

**Comment by abdo3a** [comment]
Thanks so much, @yumisims,
i follow your suggestions, and the pipeline works handsomely on the yeast sequencing test data.
